[[main]]
none = "none"

[[main]]
name = "Blog"
pageRef = "blog"
identifier = "1T1vKlSmO8"
weight = 2

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "sDlOCUapEY"
weight = 1

[[main]]
name = "REAPER"
pageRef = "reaper"
identifier = "riviiHjWIQ"
weight = 3

[[main]]
name = "Making Music On Linux"
pageRef = "linuxmusicproduction"
identifier = "BGi8Ke1RRQ"
weight = 4

[[footer]]
none = "none"
