[[main]]
none = "none"

[[main]]
name = "Blog"
pageRef = "blog"
identifier = "1T1vKlSmO8"
weight = 2

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "sDlOCUapEY"
weight = 1

[[main]]
name = "REAPER"
weight = 3

[[main]]
name = "Useful Settings And Scripts"
parent = "REAPER"
pageRef = "reaper"
weight = 3


[[main]]
name = "Making Music On Linux"
weight = 4

[[main]]
name = "Running Windows Plugins"
parent = "Making Music On Linux"
pageRef = "linuxmusicproduction/windowsplugins"
weight = 4

[[main]]
name = "Linux Plugins"
parent = "Making Music On Linux"
pageRef = "linuxmusicproduction/linuxplugs"
weight = 4


[[footer]]
none = "none"
